from .cross_entropy_loss import *
from .instance_discrimination_loss import *
from .simclr_loss import *
from .relative_location_loss import *
from .mocov2_loss import *
from .finetune_loss import *
from .rotnet_loss import *
from .simsiam_loss import *
from .autoencoder_loss import *
from .depth_pred_loss import *
from .barlow_twins_loss import *
from .vicreg_loss import *
